export const REDUCER_ACTION_TYPE = {
  LOAD_GROUPS: "LOAD_GROUPS",
  LOAD_MORE_GROUPS: "LOAD_MORE_GROUPS",
  LOAD_MEMBERS: "LOAD_MEMBERS",
  CREATE_GROUP: "CREATE_GROUP",
  UPDATE_GROUP: "UPDATE_GROUP",
  DELETE_GROUP: "DELETE_GROUP",
  REQUEST_ENTER_GROUP: "REQUEST_ENTER_GROUP",
  LOAD_GROUPS_MEMBER: "REDUCER_ACTION_TYPE.LOAD_GROUPS_MEMBER",
};
