export const REDUCER_ACTION_TYPE = {
  LOAD_GROUPS: "LOAD_GROUPS",
  LOAD_MEMBERS: "LOAD_MEMBERS",
  CREATE_MEMBER: "CREATE_GROUP",
  UPDATE_MEMBER: "UPDATE_GROUP",
  DELETE_GROUP: "DELETE_GROUP",
  REQUEST_ENTER_GROUP: "REQUEST_ENTER_GROUP",
};
